[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
# SPA fallback: ensure client-side routes are served by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API function proxy
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
