[build]
  command = "npm run build"
  publish = "client/dist/spa"

# SPA routing for your Vite/React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: make sure functions folder is not forced
[functions]
  directory = "netlify/functions"
